#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# set background/colorscheme
~/.fehbg &
wal -n -R

# hide mouse cursor
unclutter --timeout 2 &

# start compositor for transparency/blur
picom -b --experimental-backends &
# start picom
picom -b &

#network manager
nm-applet --indicator &

# launch polybar
$HOME/.config/polybar/launch.sh

#start automounter demon
udiskie &

#actual bspwm config
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/borders.sh &
