#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

MID=DP-2
LEFT=DP-0
RIGHT=DP-4

# orient monitors like:
xrandr \ 
  --output $MID --auto --primary  --pos 2560x0  \
  --output $LEFT --mode 2560x1440 --left-of $MID --rate 144.00 --pos 0x0  \
  --output $RIGHT --mode 2560x1440 --rate 144.00 --right-of $MID --pos 6400x0

# set background/colorscheme
~/.fehbg &
wal -n -R

# hide mouse cursor
unclutter --timeout 2 &

# start compositor for transparency/blur
picom -b --experimental-backends &

# launch polybar
$HOME/.config/polybar/launch.sh

#start automounter demon
udiskie &

#actual bspwm config
bspc monitor $RIGHT -d 3 6 9
bspc monitor $MID -d 2 5 8
bspc monitor $LEFT -d 0 1 4 7

bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/borders.sh &
